### ISSUE TITLE
Please add https://martinomensio.solid.community/ to the aggregator

### ISSUE THREAD

**Issue by MartinoMensio** [factsmission/twee-fi-aggregator#4]
I'm trying out the twee.fi application, what is the status of this project? Seems really interesting but I see only 4 users.

Thanks,
Martino

**Comment by retog** [comment]
Hi Martino, I'm sorry that we left this project unattended for so long. Partly the lack of activity from my side is the disappointment of not having found a scalable solution for distributing the reviews. Having users setting up their proxies and maintaining a list of sources isn't a very friendly or solid approach. If you have interest in enegizing this project, you're more than welcome to do so: I've added it to my [wuffle](https://github.com/nikku/wuffle) board so that I shouldn't miss it, if you make a pull request.

**Comment by retog** [comment]
https://github.com/factsmission/twee-fi-aggregator/commit/1a37f448fc4ae8148fb244063a2784376dd43258
